package com.oracle.xmlns.oxp.service.v2;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1224
public class ScheduleServiceClient {
    public static void main(String[] args) {
        ScheduleService_Service scheduleService_Service = new ScheduleService_Service();
        ScheduleService scheduleService = scheduleService_Service.getScheduleService();
        // Add your code to call the desired methods.


    }

    public void scheduleReportForHrLetter() {
        ScheduleService_Service scheduleService_Service = new ScheduleService_Service();
        ScheduleService scheduleService = scheduleService_Service.getScheduleService();

        // Testing runReport
        System.out.println("Testing runReport Service");
        try {

            ReportRequest req = new ReportRequest();
            req.setAttributeCalendar("Gregorian");
            req.setAttributeTimezone("GMT+5:30");
            req.setAttributeFormat("pdf"); //type of the report
            req.setAttributeLocale("en-US"); //Language
            req.setAttributeTemplate("Simple"); //Template type
            req.setReportAbsolutePath("/~weblogic/Customer Details.xdo"); //Absolute path of the report from BIP Catalog.
            req.setSizeOfDataChunkDownload(-1); //to download all

            ScheduleRequest sreq = new ScheduleRequest();
            sreq.setReportRequest(req); //Set ReportRequest
            sreq.setSaveDataOption(true);
            sreq.setDataModelUrl("/~weblogic/Customer_details.xdm");
            sreq.setBookBindingOutputOption(false);
            sreq.setJobTZ("GMT+5:30");
            sreq.setStartDate("2017-12-18T14:01:00");
            sreq.setEndDate("2017-12-18T14:30:01");
            sreq.setSaveOutputOption(true);
            sreq.setMergeOutputOption(true);
            sreq.setNotifyWhenFailed(false);
            sreq.setNotifyWhenSuccess(false);
            sreq.setNotifyWhenWarning(false);
            sreq.setRepeatCount(5);
            sreq.setUseUTF8Option(true);
            sreq.setScheduleBurstringOption(false);
            sreq.setSchedulePublicOption(true);
            sreq.setUserJobName("Month");
            sreq.setRepeatInterval(3600000);


            String job_id = null;
            ;
            try {
                job_id = scheduleService.scheduleReport(sreq, "weblogic", "weblogic123");
            } catch (AccessDeniedException_Exception | InvalidParametersException_Exception |
                     OperationFailedException_Exception e) {
            }
            System.out.println("job_id:" + job_id);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
