package SalicView;

import java.util.Collection;

import oracle.jbo.Key;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 12 02:53:09 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ManagerDashBoardCountVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ManagerDashBoardCountVOImpl() {
    }

    @Override
    public void beforeCommit(TransactionEvent transactionEvent) {
        // TODO Implement this method
        //super.beforeCommit(transactionEvent);
    }

    @Override
    public void afterCommit(TransactionEvent transactionEvent) {
        // TODO Implement this method
        //super.afterCommit(transactionEvent);
    }

    @Override
    public void afterRollback(TransactionEvent transactionEvent) {
        // TODO Implement this method
        //super.afterRollback(transactionEvent);
    }

    @Override
    public void beforeRollback(TransactionEvent transactionEvent) {
        // TODO Implement this method
        //super.beforeRollback(transactionEvent);
    }
}

