package SalicView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 12 10:53:25 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhcmOtherExpenseTVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxhcmOtherExpenseTVOImpl() {
    }
}

