package SalicView;

import java.math.BigDecimal;

import java.sql.Blob;
import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 12 10:53:22 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhcmOtherExpenseTVORowImpl extends ViewRowImpl {

    public static final int ENTITY_XXHCMOTHEREXPENSEEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Attribute1 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute1();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute1((String) value);
            }
        }
        ,
        Attribute10 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute10();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute10((String) value);
            }
        }
        ,
        Attribute2 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute2();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute2((String) value);
            }
        }
        ,
        Attribute3 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute3();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute3((String) value);
            }
        }
        ,
        Attribute4 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute4();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute4((String) value);
            }
        }
        ,
        Attribute5 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute5();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute5((String) value);
            }
        }
        ,
        Attribute6 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute6();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute6((String) value);
            }
        }
        ,
        Attribute7 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute7();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute7((String) value);
            }
        }
        ,
        Attribute8 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute8();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute8((String) value);
            }
        }
        ,
        Attribute9 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttribute9();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttribute9((String) value);
            }
        }
        ,
        AttributeCategory {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getAttributeCategory();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttributeCategory((String) value);
            }
        }
        ,
        ComplReportAttach {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getComplReportAttach();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setComplReportAttach((Blob) value);
            }
        }
        ,
        CreatedBy {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getCreatedBy();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setCreatedBy((BigDecimal) value);
            }
        }
        ,
        CreationDate {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getCreationDate();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp) value);
            }
        }
        ,
        Currency {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getCurrency();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setCurrency((String) value);
            }
        }
        ,
        ExchnRate {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getExchnRate();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setExchnRate((BigDecimal) value);
            }
        }
        ,
        ExpenseId {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getExpenseId();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setExpenseId((BigDecimal) value);
            }
        }
        ,
        ExpnDesc {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getExpnDesc();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setExpnDesc((String) value);
            }
        }
        ,
        LastUpdateDate {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp) value);
            }
        }
        ,
        LastUpdateLogin {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((BigDecimal) value);
            }
        }
        ,
        LastUpdatedBy {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((BigDecimal) value);
            }
        }
        ,
        OtherExpn {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getOtherExpn();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setOtherExpn((BigDecimal) value);
            }
        }
        ,
        ReqDtlsId {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getReqDtlsId();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setReqDtlsId((BigDecimal) value);
            }
        }
        ,
        TotalAmount {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getTotalAmount();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setTotalAmount((BigDecimal) value);
            }
        }
        ,
        TotalColumnAmount {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getTotalColumnAmount();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setTotalColumnAmount((BigDecimal) value);
            }
        }
        ,
        CurrencyListROVO1 {
            protected Object get(XxhcmOtherExpenseTVORowImpl obj) {
                return obj.getCurrencyListROVO1();
            }

            protected void put(XxhcmOtherExpenseTVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected abstract Object get(XxhcmOtherExpenseTVORowImpl object);

        protected abstract void put(XxhcmOtherExpenseTVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int COMPLREPORTATTACH = AttributesEnum.ComplReportAttach.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int EXCHNRATE = AttributesEnum.ExchnRate.index();
    public static final int EXPENSEID = AttributesEnum.ExpenseId.index();
    public static final int EXPNDESC = AttributesEnum.ExpnDesc.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OTHEREXPN = AttributesEnum.OtherExpn.index();
    public static final int REQDTLSID = AttributesEnum.ReqDtlsId.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int TOTALCOLUMNAMOUNT = AttributesEnum.TotalColumnAmount.index();
    public static final int CURRENCYLISTROVO1 = AttributesEnum.CurrencyListROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhcmOtherExpenseTVORowImpl() {
    }

    /**
     * Gets XxhcmOtherExpenseEO entity object.
     * @return the XxhcmOtherExpenseEO
     */
    public EntityImpl getXxhcmOtherExpenseEO() {
        return (EntityImpl) getEntity(ENTITY_XXHCMOTHEREXPENSEEO);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute1.
     * @param value value to set the  Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for COMPL_REPORT_ATTACH using the alias name ComplReportAttach.
     * @return the COMPL_REPORT_ATTACH
     */
    public Blob getComplReportAttach() {
        return (Blob) getAttributeInternal(COMPLREPORTATTACH);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPL_REPORT_ATTACH using the alias name ComplReportAttach.
     * @param value value to set the COMPL_REPORT_ATTACH
     */
    public void setComplReportAttach(Blob value) {
        setAttributeInternal(COMPLREPORTATTACH, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CURRENCY using the alias name Currency.
     * @return the CURRENCY
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY using the alias name Currency.
     * @param value value to set the CURRENCY
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for EXCHN_RATE using the alias name ExchnRate.
     * @return the EXCHN_RATE
     */
    public BigDecimal getExchnRate() {
        return (BigDecimal) getAttributeInternal(EXCHNRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHN_RATE using the alias name ExchnRate.
     * @param value value to set the EXCHN_RATE
     */
    public void setExchnRate(BigDecimal value) {
        setAttributeInternal(EXCHNRATE, value);
    }

    /**
     * Gets the attribute value for EXPENSE_ID using the alias name ExpenseId.
     * @return the EXPENSE_ID
     */
    public BigDecimal getExpenseId() {
        return (BigDecimal) getAttributeInternal(EXPENSEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPENSE_ID using the alias name ExpenseId.
     * @param value value to set the EXPENSE_ID
     */
    public void setExpenseId(BigDecimal value) {
        setAttributeInternal(EXPENSEID, value);
    }

    /**
     * Gets the attribute value for EXPN_DESC using the alias name ExpnDesc.
     * @return the EXPN_DESC
     */
    public String getExpnDesc() {
        return (String) getAttributeInternal(EXPNDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPN_DESC using the alias name ExpnDesc.
     * @param value value to set the EXPN_DESC
     */
    public void setExpnDesc(String value) {
        setAttributeInternal(EXPNDESC, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public BigDecimal getLastUpdateLogin() {
        return (BigDecimal) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(BigDecimal value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public BigDecimal getLastUpdatedBy() {
        return (BigDecimal) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(BigDecimal value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for OTHER_EXPN using the alias name OtherExpn.
     * @return the OTHER_EXPN
     */
    public BigDecimal getOtherExpn() {
        return (BigDecimal) getAttributeInternal(OTHEREXPN);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_EXPN using the alias name OtherExpn.
     * @param value value to set the OTHER_EXPN
     */
    public void setOtherExpn(BigDecimal value) {
        setAttributeInternal(OTHEREXPN, value);
    }

    /**
     * Gets the attribute value for REQ_DTLS_ID using the alias name ReqDtlsId.
     * @return the REQ_DTLS_ID
     */
    public BigDecimal getReqDtlsId() {
        return (BigDecimal) getAttributeInternal(REQDTLSID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_DTLS_ID using the alias name ReqDtlsId.
     * @param value value to set the REQ_DTLS_ID
     */
    public void setReqDtlsId(BigDecimal value) {
        setAttributeInternal(REQDTLSID, value);
    }

    /**
     * Gets the attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @return the TOTAL_AMOUNT
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @param value value to set the TOTAL_AMOUNT
     */
    public void setTotalAmount(BigDecimal value) {
        setAttributeInternal(TOTALAMOUNT, value);
        getTotalColumnAmount();
    }

    /**
     * Gets the attribute value for the calculated attribute TotalColumnAmount.
     * @return the TotalColumnAmount
     */
    public BigDecimal getTotalColumnAmount() {
        BigDecimal totalColAmount = new BigDecimal(0);
        RowSetIterator rs = getViewObject().createRowSetIterator(null);
        while(rs.hasNext()){
            oracle.jbo.Row row = rs.next();
            BigDecimal totalAmount = (BigDecimal) row.getAttribute("TotalAmount");
            if(totalAmount != null){
                totalColAmount = totalColAmount.add(totalAmount);
            }
        }
        return totalColAmount;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalColumnAmount.
     * @param value value to set the  TotalColumnAmount
     */
    public void setTotalColumnAmount(BigDecimal value) {
        setAttributeInternal(TOTALCOLUMNAMOUNT, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> CurrencyListROVO1.
     */
    public RowSet getCurrencyListROVO1() {
        return (RowSet) getAttributeInternal(CURRENCYLISTROVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

