package SalicEntity;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 16 19:10:47 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhcmOvertimeDetailsAllEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ReqDtlsId {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getReqDtlsId();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setReqDtlsId((Number) value);
            }
        }
        ,
        ReqId {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getReqId();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setReqId((Number) value);
            }
        }
        ,
        Status {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getStatus();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setStatus((String) value);
            }
        }
        ,
        Description {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getDescription();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setDescription((String) value);
            }
        }
        ,
        OvertimeHours {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getOvertimeHours();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setOvertimeHours((Number) value);
            }
        }
        ,
        OvertimeDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getOvertimeDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setOvertimeDate((Date) value);
            }
        }
        ,
        OvertimeType {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getOvertimeType();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setOvertimeType((String) value);
            }
        }
        ,
        CalculatedHours {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getCalculatedHours();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setCalculatedHours((Number) value);
            }
        }
        ,
        Missions {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getMissions();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setMissions((String) value);
            }
        }
        ,
        AttributeCategory {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttributeCategory();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttributeCategory((String) value);
            }
        }
        ,
        Attribute1 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute1();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute1((String) value);
            }
        }
        ,
        Attribute2 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute2();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute2((String) value);
            }
        }
        ,
        Attribute3 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute3();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute3((String) value);
            }
        }
        ,
        Attribute4 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute4();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute4((String) value);
            }
        }
        ,
        Attribute5 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute5();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute5((String) value);
            }
        }
        ,
        Attribute6 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute6();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute6((String) value);
            }
        }
        ,
        Attribute7 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute7();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute7((String) value);
            }
        }
        ,
        Attribute8 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute8();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute8((String) value);
            }
        }
        ,
        Attribute9 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute9();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute9((String) value);
            }
        }
        ,
        Attribute10 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAttribute10();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttribute10((String) value);
            }
        }
        ,
        CreatedBy {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getCreatedBy();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setCreatedBy((Number) value);
            }
        }
        ,
        CreationDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getCreationDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number) value);
            }
        }
        ,
        LastUpdateDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateLogin {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number) value);
            }
        }
        ,
        AdvAmt {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAdvAmt();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAdvAmt((BigDecimal) value);
            }
        }
        ,
        Comments {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getComments();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setComments((String) value);
            }
        }
        ,
        Months {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getMonths();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setMonths((String) value);
            }
        }
        ,
        Note {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getNote();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setNote((String) value);
            }
        }
        ,
        Leave {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getLeave();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setLeave((String) value);
            }
        }
        ,
        SalaryPeriod {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getSalaryPeriod();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setSalaryPeriod((Date) value);
            }
        }
        ,
        ActAmt {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getActAmt();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setActAmt((BigDecimal) value);
            }
        }
        ,
        Age {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAge();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAge((BigDecimal) value);
            }
        }
        ,
        AvlAmt {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAvlAmt();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAvlAmt((BigDecimal) value);
            }
        }
        ,
        Child {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getChild();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setChild((String) value);
            }
        }
        ,
        Grade {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getGrade();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setGrade((BigDecimal) value);
            }
        }
        ,
        InvDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getInvDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setInvDate((Date) value);
            }
        }
        ,
        InvNum {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getInvNum();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setInvNum((String) value);
            }
        }
        ,
        InvTotal {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getInvTotal();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setInvTotal((BigDecimal) value);
            }
        }
        ,
        MaxAmt {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getMaxAmt();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setMaxAmt((BigDecimal) value);
            }
        }
        ,
        School {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getSchool();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setSchool((String) value);
            }
        }
        ,
        Schoolgrade {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getSchoolgrade();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setSchoolgrade((String) value);
            }
        }
        ,
        Semester {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getSemester();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setSemester((String) value);
            }
        }
        ,
        SalaryEndDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getSalaryEndDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setSalaryEndDate((Date) value);
            }
        }
        ,
        SalPeriod {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getSalPeriod();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setSalPeriod((String) value);
            }
        }
        ,
        PerAbsenceEntryId {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getPerAbsenceEntryId();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setPerAbsenceEntryId((BigDecimal) value);
            }
        }
        ,
        Contactpersonid {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getContactpersonid();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setContactpersonid((BigDecimal) value);
            }
        }
        ,
        ActRetDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getActRetDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setActRetDate((Date) value);
            }
        }
        ,
        ActStartDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getActStartDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setActStartDate((Date) value);
            }
        }
        ,
        AdvPerdiem {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAdvPerdiem();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAdvPerdiem((String) value);
            }
        }
        ,
        AirlineTicketType {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getAirlineTicketType();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAirlineTicketType((String) value);
            }
        }
        ,
        DestCategory {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getDestCategory();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setDestCategory((String) value);
            }
        }
        ,
        DestCountryCity {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getDestCountryCity();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setDestCountryCity((String) value);
            }
        }
        ,
        DestVisaRequired {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getDestVisaRequired();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setDestVisaRequired((String) value);
            }
        }
        ,
        EndDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getEndDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setEndDate((Date) value);
            }
        }
        ,
        ExitRerentryVisa {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getExitRerentryVisa();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setExitRerentryVisa((String) value);
            }
        }
        ,
        LetterTo {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getLetterTo();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setLetterTo((String) value);
            }
        }
        ,
        LetterType {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getLetterType();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setLetterType((String) value);
            }
        }
        ,
        NumberOfDays {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getNumberOfDays();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setNumberOfDays((BigDecimal) value);
            }
        }
        ,
        OrigEndDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getOrigEndDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setOrigEndDate((Date) value);
            }
        }
        ,
        OrigStartDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getOrigStartDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setOrigStartDate((Date) value);
            }
        }
        ,
        Other {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getOther();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setOther((String) value);
            }
        }
        ,
        PerdiemPerDay {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getPerdiemPerDay();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setPerdiemPerDay((BigDecimal) value);
            }
        }
        ,
        ProjType {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getProjType();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setProjType((String) value);
            }
        }
        ,
        StartDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getStartDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setStartDate((Date) value);
            }
        }
        ,
        TotalPerdiem {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getTotalPerdiem();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setTotalPerdiem((BigDecimal) value);
            }
        }
        ,
        TravReqNum {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getTravReqNum();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setTravReqNum((String) value);
            }
        }
        ,
        TripType {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getTripType();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setTripType((String) value);
            }
        }
        ,
        BussTravReqNum {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getBussTravReqNum();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setBussTravReqNum((String) value);
            }
        }
        ,
        Other1 {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getOther1();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setOther1((String) value);
            }
        }
        ,
        SalaryDate {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getSalaryDate();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setSalaryDate((Date) value);
            }
        }
        ,
        DestRegion {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getDestRegion();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setDestRegion((String) value);
            }
        }
        ,
        NoOfDays {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getNoOfDays();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setNoOfDays((BigDecimal) value);
            }
        }
        ,
        DestinationCountry {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getDestinationCountry();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setDestinationCountry((BigDecimal) value);
            }
        }
        ,
        BussTravReqNumValue {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getBussTravReqNumValue();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setBussTravReqNumValue((String) value);
            }
        }
        ,
        XxhcmOvertimeHeadersAllVO {
            protected Object get(XxhcmOvertimeDetailsAllEOImpl obj) {
                return obj.getXxhcmOvertimeHeadersAllVO();
            }

            protected void put(XxhcmOvertimeDetailsAllEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(XxhcmOvertimeDetailsAllEOImpl object);

        protected abstract void put(XxhcmOvertimeDetailsAllEOImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int REQDTLSID = AttributesEnum.ReqDtlsId.index();
    public static final int REQID = AttributesEnum.ReqId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int OVERTIMEHOURS = AttributesEnum.OvertimeHours.index();
    public static final int OVERTIMEDATE = AttributesEnum.OvertimeDate.index();
    public static final int OVERTIMETYPE = AttributesEnum.OvertimeType.index();
    public static final int CALCULATEDHOURS = AttributesEnum.CalculatedHours.index();
    public static final int MISSIONS = AttributesEnum.Missions.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ADVAMT = AttributesEnum.AdvAmt.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int MONTHS = AttributesEnum.Months.index();
    public static final int NOTE = AttributesEnum.Note.index();
    public static final int LEAVE = AttributesEnum.Leave.index();
    public static final int SALARYPERIOD = AttributesEnum.SalaryPeriod.index();
    public static final int ACTAMT = AttributesEnum.ActAmt.index();
    public static final int AGE = AttributesEnum.Age.index();
    public static final int AVLAMT = AttributesEnum.AvlAmt.index();
    public static final int CHILD = AttributesEnum.Child.index();
    public static final int GRADE = AttributesEnum.Grade.index();
    public static final int INVDATE = AttributesEnum.InvDate.index();
    public static final int INVNUM = AttributesEnum.InvNum.index();
    public static final int INVTOTAL = AttributesEnum.InvTotal.index();
    public static final int MAXAMT = AttributesEnum.MaxAmt.index();
    public static final int SCHOOL = AttributesEnum.School.index();
    public static final int SCHOOLGRADE = AttributesEnum.Schoolgrade.index();
    public static final int SEMESTER = AttributesEnum.Semester.index();
    public static final int SALARYENDDATE = AttributesEnum.SalaryEndDate.index();
    public static final int SALPERIOD = AttributesEnum.SalPeriod.index();
    public static final int PERABSENCEENTRYID = AttributesEnum.PerAbsenceEntryId.index();
    public static final int CONTACTPERSONID = AttributesEnum.Contactpersonid.index();
    public static final int ACTRETDATE = AttributesEnum.ActRetDate.index();
    public static final int ACTSTARTDATE = AttributesEnum.ActStartDate.index();
    public static final int ADVPERDIEM = AttributesEnum.AdvPerdiem.index();
    public static final int AIRLINETICKETTYPE = AttributesEnum.AirlineTicketType.index();
    public static final int DESTCATEGORY = AttributesEnum.DestCategory.index();
    public static final int DESTCOUNTRYCITY = AttributesEnum.DestCountryCity.index();
    public static final int DESTVISAREQUIRED = AttributesEnum.DestVisaRequired.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int EXITRERENTRYVISA = AttributesEnum.ExitRerentryVisa.index();
    public static final int LETTERTO = AttributesEnum.LetterTo.index();
    public static final int LETTERTYPE = AttributesEnum.LetterType.index();
    public static final int NUMBEROFDAYS = AttributesEnum.NumberOfDays.index();
    public static final int ORIGENDDATE = AttributesEnum.OrigEndDate.index();
    public static final int ORIGSTARTDATE = AttributesEnum.OrigStartDate.index();
    public static final int OTHER = AttributesEnum.Other.index();
    public static final int PERDIEMPERDAY = AttributesEnum.PerdiemPerDay.index();
    public static final int PROJTYPE = AttributesEnum.ProjType.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int TOTALPERDIEM = AttributesEnum.TotalPerdiem.index();
    public static final int TRAVREQNUM = AttributesEnum.TravReqNum.index();
    public static final int TRIPTYPE = AttributesEnum.TripType.index();
    public static final int BUSSTRAVREQNUM = AttributesEnum.BussTravReqNum.index();
    public static final int OTHER1 = AttributesEnum.Other1.index();
    public static final int SALARYDATE = AttributesEnum.SalaryDate.index();
    public static final int DESTREGION = AttributesEnum.DestRegion.index();
    public static final int NOOFDAYS = AttributesEnum.NoOfDays.index();
    public static final int DESTINATIONCOUNTRY = AttributesEnum.DestinationCountry.index();
    public static final int BUSSTRAVREQNUMVALUE = AttributesEnum.BussTravReqNumValue.index();
    public static final int XXHCMOVERTIMEHEADERSALLVO = AttributesEnum.XxhcmOvertimeHeadersAllVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhcmOvertimeDetailsAllEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("SalicEntity.XxhcmOvertimeDetailsAllEO");
    }


    /**
     * Gets the attribute value for ReqDtlsId, using the alias name ReqDtlsId.
     * @return the value of ReqDtlsId
     */
    public Number getReqDtlsId() {
        return (Number) getAttributeInternal(REQDTLSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReqDtlsId.
     * @param value value to set the ReqDtlsId
     */
    public void setReqDtlsId(Number value) {
        setAttributeInternal(REQDTLSID, value);
    }

    /**
     * Gets the attribute value for ReqId, using the alias name ReqId.
     * @return the value of ReqId
     */
    public Number getReqId() {
        return (Number) getAttributeInternal(REQID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReqId.
     * @param value value to set the ReqId
     */
    public void setReqId(Number value) {
        setAttributeInternal(REQID, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the value of Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for OvertimeHours, using the alias name OvertimeHours.
     * @return the value of OvertimeHours
     */
    public Number getOvertimeHours() {
        return (Number) getAttributeInternal(OVERTIMEHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for OvertimeHours.
     * @param value value to set the OvertimeHours
     */
    public void setOvertimeHours(Number value) {
        setAttributeInternal(OVERTIMEHOURS, value);
        if(value!=null){
        Number calcHours = value.multiply(1.5);
        setCalculatedHours(calcHours);
        }
    }

    /**
     * Gets the attribute value for OvertimeDate, using the alias name OvertimeDate.
     * @return the value of OvertimeDate
     */
    public Date getOvertimeDate() {
        return (Date) getAttributeInternal(OVERTIMEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OvertimeDate.
     * @param value value to set the OvertimeDate
     */
    public void setOvertimeDate(Date value) {
        setAttributeInternal(OVERTIMEDATE, value);
    }

    /**
     * Gets the attribute value for OvertimeType, using the alias name OvertimeType.
     * @return the value of OvertimeType
     */
    public String getOvertimeType() {
        return (String) getAttributeInternal(OVERTIMETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OvertimeType.
     * @param value value to set the OvertimeType
     */
    public void setOvertimeType(String value) {
        setAttributeInternal(OVERTIMETYPE, value);
    }

    /**
     * Gets the attribute value for CalculatedHours, using the alias name CalculatedHours.
     * @return the value of CalculatedHours
     */
    public Number getCalculatedHours() {
        return (Number) getAttributeInternal(CALCULATEDHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CalculatedHours.
     * @param value value to set the CalculatedHours
     */
    public void setCalculatedHours(Number value) {
        setAttributeInternal(CALCULATEDHOURS, value);
    }

    /**
     * Gets the attribute value for Missions, using the alias name Missions.
     * @return the value of Missions
     */
    public String getMissions() {
        return (String) getAttributeInternal(MISSIONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Missions.
     * @param value value to set the Missions
     */
    public void setMissions(String value) {
        setAttributeInternal(MISSIONS, value);
    }

    /**
     * Gets the attribute value for AttributeCategory, using the alias name AttributeCategory.
     * @return the value of AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeCategory.
     * @param value value to set the AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the value of Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the value of Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the value of Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the value of Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the value of Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the value of Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the value of Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the value of Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the value of Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the value of Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for AdvAmt, using the alias name AdvAmt.
     * @return the value of AdvAmt
     */
    public BigDecimal getAdvAmt() {
        return (BigDecimal) getAttributeInternal(ADVAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdvAmt.
     * @param value value to set the AdvAmt
     */
    public void setAdvAmt(BigDecimal value) {
        setAttributeInternal(ADVAMT, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the value of Comments
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for Months, using the alias name Months.
     * @return the value of Months
     */
    public String getMonths() {
        return (String) getAttributeInternal(MONTHS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Months.
     * @param value value to set the Months
     */
    public void setMonths(String value) {
        setAttributeInternal(MONTHS, value);
    }

    /**
     * Gets the attribute value for Note, using the alias name Note.
     * @return the value of Note
     */
    public String getNote() {
        return (String) getAttributeInternal(NOTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Note.
     * @param value value to set the Note
     */
    public void setNote(String value) {
        setAttributeInternal(NOTE, value);
    }

    /**
     * Gets the attribute value for Leave, using the alias name Leave.
     * @return the value of Leave
     */
    public String getLeave() {
        return (String) getAttributeInternal(LEAVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Leave.
     * @param value value to set the Leave
     */
    public void setLeave(String value) {
        setAttributeInternal(LEAVE, value);
    }

    /**
     * Gets the attribute value for SalaryPeriod, using the alias name SalaryPeriod.
     * @return the value of SalaryPeriod
     */
    public Date getSalaryPeriod() {
        return (Date) getAttributeInternal(SALARYPERIOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalaryPeriod.
     * @param value value to set the SalaryPeriod
     */
    public void setSalaryPeriod(Date value) {
        setAttributeInternal(SALARYPERIOD, value);
    }

    /**
     * Gets the attribute value for ActAmt, using the alias name ActAmt.
     * @return the value of ActAmt
     */
    public BigDecimal getActAmt() {
        return (BigDecimal) getAttributeInternal(ACTAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActAmt.
     * @param value value to set the ActAmt
     */
    public void setActAmt(BigDecimal value) {
        setAttributeInternal(ACTAMT, value);
    }

    /**
     * Gets the attribute value for Age, using the alias name Age.
     * @return the value of Age
     */
    public BigDecimal getAge() {
        return (BigDecimal) getAttributeInternal(AGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Age.
     * @param value value to set the Age
     */
    public void setAge(BigDecimal value) {
        setAttributeInternal(AGE, value);
    }

    /**
     * Gets the attribute value for AvlAmt, using the alias name AvlAmt.
     * @return the value of AvlAmt
     */
    public BigDecimal getAvlAmt() {
        return (BigDecimal) getAttributeInternal(AVLAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AvlAmt.
     * @param value value to set the AvlAmt
     */
    public void setAvlAmt(BigDecimal value) {
        setAttributeInternal(AVLAMT, value);
    }

    /**
     * Gets the attribute value for Child, using the alias name Child.
     * @return the value of Child
     */
    public String getChild() {
        return (String) getAttributeInternal(CHILD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Child.
     * @param value value to set the Child
     */
    public void setChild(String value) {
        setAttributeInternal(CHILD, value);
    }

    /**
     * Gets the attribute value for Grade, using the alias name Grade.
     * @return the value of Grade
     */
    public BigDecimal getGrade() {
        return (BigDecimal) getAttributeInternal(GRADE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Grade.
     * @param value value to set the Grade
     */
    public void setGrade(BigDecimal value) {
        setAttributeInternal(GRADE, value);
    }

    /**
     * Gets the attribute value for InvDate, using the alias name InvDate.
     * @return the value of InvDate
     */
    public Date getInvDate() {
        return (Date) getAttributeInternal(INVDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvDate.
     * @param value value to set the InvDate
     */
    public void setInvDate(Date value) {
        setAttributeInternal(INVDATE, value);
    }

    /**
     * Gets the attribute value for InvNum, using the alias name InvNum.
     * @return the value of InvNum
     */
    public String getInvNum() {
        return (String) getAttributeInternal(INVNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvNum.
     * @param value value to set the InvNum
     */
    public void setInvNum(String value) {
        setAttributeInternal(INVNUM, value);
    }

    /**
     * Gets the attribute value for InvTotal, using the alias name InvTotal.
     * @return the value of InvTotal
     */
    public BigDecimal getInvTotal() {
        return (BigDecimal) getAttributeInternal(INVTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvTotal.
     * @param value value to set the InvTotal
     */
    public void setInvTotal(BigDecimal value) {
        setAttributeInternal(INVTOTAL, value);
    }

    /**
     * Gets the attribute value for MaxAmt, using the alias name MaxAmt.
     * @return the value of MaxAmt
     */
    public BigDecimal getMaxAmt() {
        return (BigDecimal) getAttributeInternal(MAXAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxAmt.
     * @param value value to set the MaxAmt
     */
    public void setMaxAmt(BigDecimal value) {
        setAttributeInternal(MAXAMT, value);
    }

    /**
     * Gets the attribute value for School, using the alias name School.
     * @return the value of School
     */
    public String getSchool() {
        return (String) getAttributeInternal(SCHOOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for School.
     * @param value value to set the School
     */
    public void setSchool(String value) {
        setAttributeInternal(SCHOOL, value);
    }

    /**
     * Gets the attribute value for Schoolgrade, using the alias name Schoolgrade.
     * @return the value of Schoolgrade
     */
    public String getSchoolgrade() {
        return (String) getAttributeInternal(SCHOOLGRADE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Schoolgrade.
     * @param value value to set the Schoolgrade
     */
    public void setSchoolgrade(String value) {
        setAttributeInternal(SCHOOLGRADE, value);
    }

    /**
     * Gets the attribute value for Semester, using the alias name Semester.
     * @return the value of Semester
     */
    public String getSemester() {
        return (String) getAttributeInternal(SEMESTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Semester.
     * @param value value to set the Semester
     */
    public void setSemester(String value) {
        setAttributeInternal(SEMESTER, value);
    }

    /**
     * Gets the attribute value for SalaryEndDate, using the alias name SalaryEndDate.
     * @return the value of SalaryEndDate
     */
    public Date getSalaryEndDate() {
        return (Date) getAttributeInternal(SALARYENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalaryEndDate.
     * @param value value to set the SalaryEndDate
     */
    public void setSalaryEndDate(Date value) {
        setAttributeInternal(SALARYENDDATE, value);
    }

    /**
     * Gets the attribute value for SalPeriod, using the alias name SalPeriod.
     * @return the value of SalPeriod
     */
    public String getSalPeriod() {
        return (String) getAttributeInternal(SALPERIOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalPeriod.
     * @param value value to set the SalPeriod
     */
    public void setSalPeriod(String value) {
        setAttributeInternal(SALPERIOD, value);
    }

    /**
     * Gets the attribute value for PerAbsenceEntryId, using the alias name PerAbsenceEntryId.
     * @return the value of PerAbsenceEntryId
     */
    public BigDecimal getPerAbsenceEntryId() {
        return (BigDecimal) getAttributeInternal(PERABSENCEENTRYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PerAbsenceEntryId.
     * @param value value to set the PerAbsenceEntryId
     */
    public void setPerAbsenceEntryId(BigDecimal value) {
        setAttributeInternal(PERABSENCEENTRYID, value);
    }

    /**
     * Gets the attribute value for Contactpersonid, using the alias name Contactpersonid.
     * @return the value of Contactpersonid
     */
    public BigDecimal getContactpersonid() {
        return (BigDecimal) getAttributeInternal(CONTACTPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Contactpersonid.
     * @param value value to set the Contactpersonid
     */
    public void setContactpersonid(BigDecimal value) {
        setAttributeInternal(CONTACTPERSONID, value);
    }

    /**
     * Gets the attribute value for ActRetDate, using the alias name ActRetDate.
     * @return the value of ActRetDate
     */
    public Date getActRetDate() {
        return (Date) getAttributeInternal(ACTRETDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActRetDate.
     * @param value value to set the ActRetDate
     */
    public void setActRetDate(Date value) {
        setAttributeInternal(ACTRETDATE, value);
    }

    /**
     * Gets the attribute value for ActStartDate, using the alias name ActStartDate.
     * @return the value of ActStartDate
     */
    public Date getActStartDate() {
        return (Date) getAttributeInternal(ACTSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActStartDate.
     * @param value value to set the ActStartDate
     */
    public void setActStartDate(Date value) {
        setAttributeInternal(ACTSTARTDATE, value);
    }

    /**
     * Gets the attribute value for AdvPerdiem, using the alias name AdvPerdiem.
     * @return the value of AdvPerdiem
     */
    public String getAdvPerdiem() {
        return (String) getAttributeInternal(ADVPERDIEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdvPerdiem.
     * @param value value to set the AdvPerdiem
     */
    public void setAdvPerdiem(String value) {
        setAttributeInternal(ADVPERDIEM, value);
    }

    /**
     * Gets the attribute value for AirlineTicketType, using the alias name AirlineTicketType.
     * @return the value of AirlineTicketType
     */
    public String getAirlineTicketType() {
        return (String) getAttributeInternal(AIRLINETICKETTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AirlineTicketType.
     * @param value value to set the AirlineTicketType
     */
    public void setAirlineTicketType(String value) {
        setAttributeInternal(AIRLINETICKETTYPE, value);
    }

    /**
     * Gets the attribute value for DestCategory, using the alias name DestCategory.
     * @return the value of DestCategory
     */
    public String getDestCategory() {
        return (String) getAttributeInternal(DESTCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DestCategory.
     * @param value value to set the DestCategory
     */
    public void setDestCategory(String value) {
        setAttributeInternal(DESTCATEGORY, value);
    }

    /**
     * Gets the attribute value for DestCountryCity, using the alias name DestCountryCity.
     * @return the value of DestCountryCity
     */
    public String getDestCountryCity() {
        return (String) getAttributeInternal(DESTCOUNTRYCITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DestCountryCity.
     * @param value value to set the DestCountryCity
     */
    public void setDestCountryCity(String value) {
        setAttributeInternal(DESTCOUNTRYCITY, value);
    }

    /**
     * Gets the attribute value for DestVisaRequired, using the alias name DestVisaRequired.
     * @return the value of DestVisaRequired
     */
    public String getDestVisaRequired() {
        return (String) getAttributeInternal(DESTVISAREQUIRED);
    }

    /**
     * Sets <code>value</code> as the attribute value for DestVisaRequired.
     * @param value value to set the DestVisaRequired
     */
    public void setDestVisaRequired(String value) {
        setAttributeInternal(DESTVISAREQUIRED, value);
    }

    /**
     * Gets the attribute value for EndDate, using the alias name EndDate.
     * @return the value of EndDate
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDate.
     * @param value value to set the EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for ExitRerentryVisa, using the alias name ExitRerentryVisa.
     * @return the value of ExitRerentryVisa
     */
    public String getExitRerentryVisa() {
        return (String) getAttributeInternal(EXITRERENTRYVISA);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExitRerentryVisa.
     * @param value value to set the ExitRerentryVisa
     */
    public void setExitRerentryVisa(String value) {
        setAttributeInternal(EXITRERENTRYVISA, value);
    }

    /**
     * Gets the attribute value for LetterTo, using the alias name LetterTo.
     * @return the value of LetterTo
     */
    public String getLetterTo() {
        return (String) getAttributeInternal(LETTERTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LetterTo.
     * @param value value to set the LetterTo
     */
    public void setLetterTo(String value) {
        setAttributeInternal(LETTERTO, value);
    }

    /**
     * Gets the attribute value for LetterType, using the alias name LetterType.
     * @return the value of LetterType
     */
    public String getLetterType() {
        return (String) getAttributeInternal(LETTERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LetterType.
     * @param value value to set the LetterType
     */
    public void setLetterType(String value) {
        setAttributeInternal(LETTERTYPE, value);
    }

    /**
     * Gets the attribute value for NumberOfDays, using the alias name NumberOfDays.
     * @return the value of NumberOfDays
     */
    public BigDecimal getNumberOfDays() {
        return (BigDecimal) getAttributeInternal(NUMBEROFDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumberOfDays.
     * @param value value to set the NumberOfDays
     */
    public void setNumberOfDays(BigDecimal value) {
        setAttributeInternal(NUMBEROFDAYS, value);
    }

    /**
     * Gets the attribute value for OrigEndDate, using the alias name OrigEndDate.
     * @return the value of OrigEndDate
     */
    public Date getOrigEndDate() {
        return (Date) getAttributeInternal(ORIGENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrigEndDate.
     * @param value value to set the OrigEndDate
     */
    public void setOrigEndDate(Date value) {
        setAttributeInternal(ORIGENDDATE, value);
    }

    /**
     * Gets the attribute value for OrigStartDate, using the alias name OrigStartDate.
     * @return the value of OrigStartDate
     */
    public Date getOrigStartDate() {
        return (Date) getAttributeInternal(ORIGSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrigStartDate.
     * @param value value to set the OrigStartDate
     */
    public void setOrigStartDate(Date value) {
        setAttributeInternal(ORIGSTARTDATE, value);
    }

    /**
     * Gets the attribute value for Other, using the alias name Other.
     * @return the value of Other
     */
    public String getOther() {
        return (String) getAttributeInternal(OTHER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Other.
     * @param value value to set the Other
     */
    public void setOther(String value) {
        setAttributeInternal(OTHER, value);
    }

    /**
     * Gets the attribute value for PerdiemPerDay, using the alias name PerdiemPerDay.
     * @return the value of PerdiemPerDay
     */
    public BigDecimal getPerdiemPerDay() {
        return (BigDecimal) getAttributeInternal(PERDIEMPERDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PerdiemPerDay.
     * @param value value to set the PerdiemPerDay
     */
    public void setPerdiemPerDay(BigDecimal value) {
        setAttributeInternal(PERDIEMPERDAY, value);
    }

    /**
     * Gets the attribute value for ProjType, using the alias name ProjType.
     * @return the value of ProjType
     */
    public String getProjType() {
        return (String) getAttributeInternal(PROJTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjType.
     * @param value value to set the ProjType
     */
    public void setProjType(String value) {
        setAttributeInternal(PROJTYPE, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the value of StartDate
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for TotalPerdiem, using the alias name TotalPerdiem.
     * @return the value of TotalPerdiem
     */
    public BigDecimal getTotalPerdiem() {
        return (BigDecimal) getAttributeInternal(TOTALPERDIEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalPerdiem.
     * @param value value to set the TotalPerdiem
     */
    public void setTotalPerdiem(BigDecimal value) {
        setAttributeInternal(TOTALPERDIEM, value);
    }

    /**
     * Gets the attribute value for TravReqNum, using the alias name TravReqNum.
     * @return the value of TravReqNum
     */
    public String getTravReqNum() {
        return (String) getAttributeInternal(TRAVREQNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for TravReqNum.
     * @param value value to set the TravReqNum
     */
    public void setTravReqNum(String value) {
        setAttributeInternal(TRAVREQNUM, value);
    }

    /**
     * Gets the attribute value for TripType, using the alias name TripType.
     * @return the value of TripType
     */
    public String getTripType() {
        return (String) getAttributeInternal(TRIPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TripType.
     * @param value value to set the TripType
     */
    public void setTripType(String value) {
        setAttributeInternal(TRIPTYPE, value);
    }

    /**
     * Gets the attribute value for BussTravReqNum, using the alias name BussTravReqNum.
     * @return the value of BussTravReqNum
     */
    public String getBussTravReqNum() {
        return (String) getAttributeInternal(BUSSTRAVREQNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for BussTravReqNum.
     * @param value value to set the BussTravReqNum
     */
    public void setBussTravReqNum(String value) {
        setAttributeInternal(BUSSTRAVREQNUM, value);
    }

    /**
     * Gets the attribute value for Other1, using the alias name Other1.
     * @return the value of Other1
     */
    public String getOther1() {
        return (String) getAttributeInternal(OTHER1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Other1.
     * @param value value to set the Other1
     */
    public void setOther1(String value) {
        setAttributeInternal(OTHER1, value);
    }

    /**
     * Gets the attribute value for SalaryDate, using the alias name SalaryDate.
     * @return the value of SalaryDate
     */
    public Date getSalaryDate() {
        return (Date) getAttributeInternal(SALARYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalaryDate.
     * @param value value to set the SalaryDate
     */
    public void setSalaryDate(Date value) {
        setAttributeInternal(SALARYDATE, value);
    }

    /**
     * Gets the attribute value for DestRegion, using the alias name DestRegion.
     * @return the value of DestRegion
     */
    public String getDestRegion() {
        return (String) getAttributeInternal(DESTREGION);
    }

    /**
     * Sets <code>value</code> as the attribute value for DestRegion.
     * @param value value to set the DestRegion
     */
    public void setDestRegion(String value) {
        setAttributeInternal(DESTREGION, value);
    }


    /**
     * Gets the attribute value for NoOfDays, using the alias name NoOfDays.
     * @return the value of NoOfDays
     */
    public BigDecimal getNoOfDays() {
        return (BigDecimal) getAttributeInternal(NOOFDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoOfDays.
     * @param value value to set the NoOfDays
     */
    public void setNoOfDays(BigDecimal value) {
        setAttributeInternal(NOOFDAYS, value);
    }

    /**
     * Gets the attribute value for DestinationCountry, using the alias name DestinationCountry.
     * @return the value of DestinationCountry
     */
    public BigDecimal getDestinationCountry() {
        return (BigDecimal) getAttributeInternal(DESTINATIONCOUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DestinationCountry.
     * @param value value to set the DestinationCountry
     */
    public void setDestinationCountry(BigDecimal value) {
        setAttributeInternal(DESTINATIONCOUNTRY, value);
    }

    /**
     * Gets the attribute value for BussTravReqNumValue, using the alias name BussTravReqNumValue.
     * @return the value of BussTravReqNumValue
     */
    public String getBussTravReqNumValue() {
        return (String) getAttributeInternal(BUSSTRAVREQNUMVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BussTravReqNumValue.
     * @param value value to set the BussTravReqNumValue
     */
    public void setBussTravReqNumValue(String value) {
        setAttributeInternal(BUSSTRAVREQNUMVALUE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * Uses the link overtimeHdrDtl to return rows of XxhcmOvertimeDetailsAllVO
     */
    public ViewRowImpl getXxhcmOvertimeHeadersAllVO() {
        return (ViewRowImpl) getAttributeInternal(XXHCMOVERTIMEHEADERSALLVO);
    }

    /**
     * @param reqDtlsId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number reqDtlsId) {
        return new Key(new Object[] { reqDtlsId });
    }


}

