package SalicROVO;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 15 11:09:55 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CheckClaimedAmountVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CheckClaimedAmountVOImpl() {
    }

    /**
     * Returns the bind variable value for bindStartDate.
     * @return bind variable value for bindStartDate
     */
    public String getbindStartDate() {
        return (String) getNamedWhereClauseParam("bindStartDate");
    }

    /**
     * Sets <code>value</code> for bind variable bindStartDate.
     * @param value value to bind as bindStartDate
     */
    public void setbindStartDate(String value) {
        setNamedWhereClauseParam("bindStartDate", value);
    }

    /**
     * Returns the bind variable value for bindEndDate.
     * @return bind variable value for bindEndDate
     */
    public String getbindEndDate() {
        return (String) getNamedWhereClauseParam("bindEndDate");
    }

    /**
     * Sets <code>value</code> for bind variable bindEndDate.
     * @param value value to bind as bindEndDate
     */
    public void setbindEndDate(String value) {
        setNamedWhereClauseParam("bindEndDate", value);
    }

    /**
     * Returns the bind variable value for bindChildId.
     * @return bind variable value for bindChildId
     */
    public BigDecimal getbindChildId() {
        return (BigDecimal) getNamedWhereClauseParam("bindChildId");
    }

    /**
     * Sets <code>value</code> for bind variable bindChildId.
     * @param value value to bind as bindChildId
     */
    public void setbindChildId(BigDecimal value) {
        setNamedWhereClauseParam("bindChildId", value);
    }
}

