package SalicROVO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 14 21:53:54 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CheckGradeAllowanceVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CheckGradeAllowanceVOImpl() {
    }


    /**
     * Returns the bind variable value for bindEmpId.
     * @return bind variable value for bindEmpId
     */
    public BigDecimal getbindEmpId() {
        return (BigDecimal) getNamedWhereClauseParam("bindEmpId");
    }

    /**
     * Sets <code>value</code> for bind variable bindEmpId.
     * @param value value to bind as bindEmpId
     */
    public void setbindEmpId(BigDecimal value) {
        setNamedWhereClauseParam("bindEmpId", value);
    }
}

