package SalicROVO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 17 09:16:41 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FetchAdvPerdiemVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FetchAdvPerdiemVOImpl() {
    }

    /**
     * Returns the bind variable value for bindReqId.
     * @return bind variable value for bindReqId
     */
    public BigDecimal getbindReqId() {
        return (BigDecimal) getNamedWhereClauseParam("bindReqId");
    }

    /**
     * Sets <code>value</code> for bind variable bindReqId.
     * @param value value to bind as bindReqId
     */
    public void setbindReqId(BigDecimal value) {
        setNamedWhereClauseParam("bindReqId", value);
    }
}

