package SalicROVO;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 21 14:33:48 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getApprovalSetupDetailsROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprLevel {
            protected Object get(getApprovalSetupDetailsROVORowImpl obj) {
                return obj.getApprLevel();
            }

            protected void put(getApprovalSetupDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ApprGroupId {
            protected Object get(getApprovalSetupDetailsROVORowImpl obj) {
                return obj.getApprGroupId();
            }

            protected void put(getApprovalSetupDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustApprGroupId {
            protected Object get(getApprovalSetupDetailsROVORowImpl obj) {
                return obj.getCustApprGroupId();
            }

            protected void put(getApprovalSetupDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PayrollGroup {
            protected Object get(getApprovalSetupDetailsROVORowImpl obj) {
                return obj.getPayrollGroup();
            }

            protected void put(getApprovalSetupDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TicketGroup {
            protected Object get(getApprovalSetupDetailsROVORowImpl obj) {
                return obj.getTicketGroup();
            }

            protected void put(getApprovalSetupDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(getApprovalSetupDetailsROVORowImpl object);

        protected abstract void put(getApprovalSetupDetailsROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPRLEVEL = AttributesEnum.ApprLevel.index();
    public static final int APPRGROUPID = AttributesEnum.ApprGroupId.index();
    public static final int CUSTAPPRGROUPID = AttributesEnum.CustApprGroupId.index();
    public static final int PAYROLLGROUP = AttributesEnum.PayrollGroup.index();
    public static final int TICKETGROUP = AttributesEnum.TicketGroup.index();

    /**
     * This is the default constructor (do not remove).
     */
    public getApprovalSetupDetailsROVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ApprLevel.
     * @return the ApprLevel
     */
    public BigDecimal getApprLevel() {
        return (BigDecimal) getAttributeInternal(APPRLEVEL);
    }

    /**
     * Gets the attribute value for the calculated attribute ApprGroupId.
     * @return the ApprGroupId
     */
    public BigDecimal getApprGroupId() {
        return (BigDecimal) getAttributeInternal(APPRGROUPID);
    }

    /**
     * Gets the attribute value for the calculated attribute CustApprGroupId.
     * @return the CustApprGroupId
     */
    public BigDecimal getCustApprGroupId() {
        return (BigDecimal) getAttributeInternal(CUSTAPPRGROUPID);
    }

    /**
     * Gets the attribute value for the calculated attribute PayrollGroup.
     * @return the PayrollGroup
     */
    public String getPayrollGroup() {
        return (String) getAttributeInternal(PAYROLLGROUP);
    }

    /**
     * Gets the attribute value for the calculated attribute TicketGroup.
     * @return the TicketGroup
     */
    public String getTicketGroup() {
        return (String) getAttributeInternal(TICKETGROUP);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

