package SalicROVO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 21 14:37:03 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getApprovalGrpDetailsROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprovalLevel {
            protected Object get(getApprovalGrpDetailsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(getApprovalGrpDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmployeeId {
            protected Object get(getApprovalGrpDetailsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(getApprovalGrpDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmployeeName {
            protected Object get(getApprovalGrpDetailsROVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(getApprovalGrpDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(getApprovalGrpDetailsROVORowImpl object);

        protected abstract void put(getApprovalGrpDetailsROVORowImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int APPROVALLEVEL = AttributesEnum.ApprovalLevel.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public getApprovalGrpDetailsROVORowImpl() {
    }
}

