package SalicROVO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 21 14:39:49 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GetJobLevelROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GetJobLevelROVOImpl() {
    }
}

