package SalicROVO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 11 17:30:01 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getUserARStatusROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public getUserARStatusROVOImpl() {
    }
}

