package SalicROVO;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 08 23:26:54 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidateOverTimeReqVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ValidateOverTimeReqVOImpl() {
    }

    /**
     * Returns the bind variable value for bind_otdate.
     * @return bind variable value for bind_otdate
     */
    public Date getbind_otdate() {
        return (Date) getNamedWhereClauseParam("bind_otdate");
    }

    /**
     * Sets <code>value</code> for bind variable bind_otdate.
     * @param value value to bind as bind_otdate
     */
    public void setbind_otdate(Date value) {
        setNamedWhereClauseParam("bind_otdate", value);
    }

    /**
     * Returns the bind variable value for bind_empid.
     * @return bind variable value for bind_empid
     */
    public BigDecimal getbind_empid() {
        return (BigDecimal) getNamedWhereClauseParam("bind_empid");
    }

    /**
     * Sets <code>value</code> for bind variable bind_empid.
     * @param value value to bind as bind_empid
     */
    public void setbind_empid(BigDecimal value) {
        setNamedWhereClauseParam("bind_empid", value);
    }
}

