package SalicROVO;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 11 11:58:45 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidateEduAllowanceComboVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ValidateEduAllowanceComboVOImpl() {
    }

    /**
     * Returns the bind variable value for bindInvNum.
     * @return bind variable value for bindInvNum
     */
    public String getbindInvNum() {
        return (String) getNamedWhereClauseParam("bindInvNum");
    }

    /**
     * Sets <code>value</code> for bind variable bindInvNum.
     * @param value value to bind as bindInvNum
     */
    public void setbindInvNum(String value) {
        setNamedWhereClauseParam("bindInvNum", value);
    }

    /**
     * Returns the bind variable value for bindChildId.
     * @return bind variable value for bindChildId
     */
    public BigDecimal getbindChildId() {
        return (BigDecimal) getNamedWhereClauseParam("bindChildId");
    }

    /**
     * Sets <code>value</code> for bind variable bindChildId.
     * @param value value to bind as bindChildId
     */
    public void setbindChildId(BigDecimal value) {
        setNamedWhereClauseParam("bindChildId", value);
    }

    /**
     * Returns the bind variable value for bindInvDate.
     * @return bind variable value for bindInvDate
     */
    public Date getbindInvDate() {
        return (Date) getNamedWhereClauseParam("bindInvDate");
    }

    /**
     * Sets <code>value</code> for bind variable bindInvDate.
     * @param value value to bind as bindInvDate
     */
    public void setbindInvDate(Date value) {
        setNamedWhereClauseParam("bindInvDate", value);
    }

    /**
     * Returns the bind variable value for bindSemester.
     * @return bind variable value for bindSemester
     */
    public String getbindSemester() {
        return (String) getNamedWhereClauseParam("bindSemester");
    }

    /**
     * Sets <code>value</code> for bind variable bindSemester.
     * @param value value to bind as bindSemester
     */
    public void setbindSemester(String value) {
        setNamedWhereClauseParam("bindSemester", value);
    }
}

