package SalicROVO;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 10 11:16:05 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidateOTonLeaveROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ValidateOTonLeaveROVOImpl() {
    }
}

