package SalicAM.client;

import SalicAM.common.EmployeeDashboardAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 18 18:32:47 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeDashboardAMClient extends ApplicationModuleImpl implements EmployeeDashboardAM {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeDashboardAMClient() {
    }

    public void load() {
        Object _ret = this.riInvokeExportedMethod(this,"load",null,null);
        return;
    }
}
