package SalicAM.client;

import SalicAM.common.HrAdminAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 11 21:58:35 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrAdminAMClient extends ApplicationModuleImpl implements HrAdminAM {
    /**
     * This is the default constructor (do not remove).
     */
    public HrAdminAMClient() {
    }

    public void load() {
        Object _ret = this.riInvokeExportedMethod(this,"load",null,null);
        return;
    }
}
