package SalicAM.client;

import SalicAM.common.overTimeAM;

import oracle.jbo.domain.Number;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 19 10:12:44 GST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class overTimeAMClient extends ApplicationModuleImpl implements overTimeAM {
    /**
     * This is the default constructor (do not remove).
     */
    public overTimeAMClient() {
    }


    public String getAirTicketType(String grade, String dest) {
        Object _ret =
            this.riInvokeExportedMethod(this, "getAirTicketType",
                                        new String[] { "java.lang.String", "java.lang.String" },
                                        new Object[] { grade, dest });
        return (String) _ret;
    }

    public Number getCurrwncyRate(String fromcurr, String grade) {
        Object _ret =
            this.riInvokeExportedMethod(this, "getCurrwncyRate",
                                        new String[] { "java.lang.String", "java.lang.String" },
                                        new Object[] { fromcurr, grade });
        return (Number) _ret;
    }

    public String getOTGradeEligibility(String grade) {
        Object _ret =
            this.riInvokeExportedMethod(this, "getOTGradeEligibility", new String[] { "java.lang.String" },
                                        new Object[] { grade });
        return (String) _ret;
    }

    public Number getPerDMRate(String dest, String grade) {
        Object _ret =
            this.riInvokeExportedMethod(this, "getPerDMRate", new String[] { "java.lang.String", "java.lang.String" },
                                        new Object[] { dest, grade });
        return (Number) _ret;
    }

    public void insertRecords() {
        Object _ret = this.riInvokeExportedMethod(this, "insertRecords", null, null);
        return;
    }
}
