package SalicAM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 18 18:32:45 IST 2017
// ---------------------------------------------------------------------
public interface EmployeeDashboardAM extends ApplicationModule {
    void load();
}
