package SalicAM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 11 21:58:35 IST 2017
// ---------------------------------------------------------------------
public interface HrAdminAM extends ApplicationModule {
    void load();
}
