package SalicAM.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 09 14:02:44 IST 2017
// ---------------------------------------------------------------------
public interface ManagerDashbordAM extends ApplicationModule {
    void load();

    void prepareMailTemplateAndSend(String approveOrReject);

    void deleteActionReqHist(BigDecimal reqId);


    void updateHeaderStatus(BigDecimal reqId, BigDecimal approvalTemplateId, String reqStatus, String status);

    void populateApproversForReqest(String reqStatus, String reqNumber, oracle.jbo.domain.Number empId, String reqType,
                                    oracle.jbo.domain.Number req_id);
}
