package SalicAM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 09 14:02:44 IST 2017
// ---------------------------------------------------------------------
public interface ManagerDashbordAM extends ApplicationModule {
    void load();

    void prepareMailTemplateAndSend(String approveOrReject);
}
