package SalicAM.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 11 20:00:16 IST 2018
// ---------------------------------------------------------------------
public interface payRollAM extends ApplicationModule {
    void prepareMailTemplateAndSend(BigDecimal reqId);
}

