package SalicAM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 12 12:38:12 IST 2017
// ---------------------------------------------------------------------
public interface payRollAM extends ApplicationModule {
    void load();
}
