package SalicAM;

import SalicAM.common.ManagerDashbordAM;

import oracle.adf.share.ADFContext;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 09 14:00:00 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ManagerDashbordAMImpl extends ApplicationModuleImpl implements ManagerDashbordAM {
    /**
     * This is the default constructor (do not remove).
     */
    public ManagerDashbordAMImpl() {
    }

    /**
     * Container's getter for XxhcmApprovalDtlsVO1.
     * @return XxhcmApprovalDtlsVO1
     */
    public ViewObjectImpl getXxhcmApprovalDtlsVO1() {
        return (ViewObjectImpl)findViewObject("XxhcmApprovalDtlsVO1");
    }

    /**
     * Container's getter for XxhcmManagerReqDtlsVO1.
     * @return XxhcmManagerReqDtlsVO1
     */
    public ViewObjectImpl getXxhcmManagerReqDtlsVO1() {
        return (ViewObjectImpl)findViewObject("XxhcmManagerReqDtlsVO1");
    }

    /**
     * Container's getter for XxQpActionHistoryTVO1.
     * @return XxQpActionHistoryTVO1
     */
    public ViewObjectImpl getXxQpActionHistoryTVO1() {
        return (ViewObjectImpl)findViewObject("XxQpActionHistoryTVO1");
    }
    public void load(){
        ViewObject mgrVo=this.getmanagerDashbaordROVO2();
        System.err.println("total request "+mgrVo.getEstimatedRowCount());
        ADFContext aDFContext = ADFContext.getCurrent();
        aDFContext.getPageFlowScope().put("total", mgrVo.getEstimatedRowCount());
        
        ViewCriteria vc=mgrVo.createViewCriteria();
        ViewCriteriaRow vcr=vc.createViewCriteriaRow();
        vcr.setAttribute("Status", "APPROVE");
        vc.addRow(vcr);
        mgrVo.applyViewCriteria(vc);
        mgrVo.executeQuery();
        System.err.println("Approved request "+mgrVo.getEstimatedRowCount());
        aDFContext.getPageFlowScope().put("approved", mgrVo.getEstimatedRowCount());
        
        ViewCriteria vcc=mgrVo.createViewCriteria();
        ViewCriteriaRow vccr=vcc.createViewCriteriaRow();
        vccr.setAttribute("Status", "REJECT");
        vcc.addRow(vccr);
        mgrVo.applyViewCriteria(vcc);
        mgrVo.executeQuery();
        System.err.println("Rejected request "+mgrVo.getEstimatedRowCount());
        aDFContext.getPageFlowScope().put("rejected", mgrVo.getEstimatedRowCount());
        
        ViewCriteria vccc=mgrVo.createViewCriteria();
        ViewCriteriaRow vcccr=vccc.createViewCriteriaRow();
        vcccr.setAttribute("Status", "Pending Approval");
        vccc.addRow(vcccr);
        mgrVo.applyViewCriteria(vccc);
        mgrVo.executeQuery();
        System.err.println("Pending request "+mgrVo.getEstimatedRowCount());
        aDFContext.getPageFlowScope().put("pending", mgrVo.getEstimatedRowCount());
        
        ViewCriteria vcccc=mgrVo.createViewCriteria();
        ViewCriteriaRow vccccr=vcccc.createViewCriteriaRow();
        vccccr.setAttribute("RequestNumber", "");
        vcccc.addRow(vccccr);
        mgrVo.applyViewCriteria(vcccc);
        mgrVo.executeQuery();
        //        mgrVo.getEstimatedRowCount();
//        AdfFacesContext.getCurrentInstance().addPartialTarget(totaReq);
    }

    /**
     * Container's getter for XxQpActionHistoryTVO2.
     * @return XxQpActionHistoryTVO2
     */
    public ViewObjectImpl getXxQpActionHistoryTVO2() {
        return (ViewObjectImpl)findViewObject("XxQpActionHistoryTVO2");
    }

    /**
     * Container's getter for managerDashbaordROVO1.
     * @return managerDashbaordROVO1
     */
    public ViewObjectImpl getmanagerDashbaordROVO1() {
        return (ViewObjectImpl)findViewObject("managerDashbaordROVO1");
    }

    /**
     * Container's getter for managerDashbaordROVO2.
     * @return managerDashbaordROVO2
     */
    public ViewObjectImpl getmanagerDashbaordROVO2() {
        return (ViewObjectImpl)findViewObject("managerDashbaordROVO2");
    }

    /**
     * Container's getter for managerDashbaordROVO3.
     * @return managerDashbaordROVO3
     */
    public ViewObjectImpl getmanagerDashbaordROVO3() {
        return (ViewObjectImpl)findViewObject("managerDashbaordROVO3");
    }


    /**
     * Container's getter for XxQpActionHistoryTVO4.
     * @return XxQpActionHistoryTVO4
     */
    public ViewObjectImpl getXxQpActionHistoryTVO4() {
        return (ViewObjectImpl)findViewObject("XxQpActionHistoryTVO4");
    }

    /**
     * Container's getter for manager_QpActionHistory_VL2.
     * @return manager_QpActionHistory_VL2
     */
    public ViewLinkImpl getmanager_QpActionHistory_VL2() {
        return (ViewLinkImpl)findViewLink("manager_QpActionHistory_VL2");
    }
}
